# Generated by Django 4.1.12 on 2023-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ac_type', models.CharField(max_length=255)),
                ('ac_no', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_tokens', models.IntegerField()),
                ('ac_status', models.CharField(max_length=255)),
                ('ac_pin', models.IntegerField()),
                ('id_proof', models.CharField(max_length=255)),
            ],
        ),
    ]
