# Generated by Django 4.1.12 on 2023-10-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(default='active', max_length=255),
            preserve_default=False,
        ),
    ]
